name: Continuous Integration

on:
  pull_request:
    branches:
      - alpha
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '>=16'

      - name: Install node modules
        run: |
          yarn install

      - name: Run CI with Lefthook
        run: |
          npx lefthook run ci-hook

      - name: Run test
        run: |
          yarn test-ci
